const data = [
    { "Error Category": "🔒 Security Issues", "Priority": "🔴 High", "Filepath": "`super install.sh`", "Function Name": "<no specific function>", "Line Number": "5", "Fail": "The script is downloading a file from an unverified source.", "Fix": "`Ensure that the source` of the file is trusted and verified." },
    { "Error Category": "🔒 Security Issues", "Priority": "🔴 High", "Filepath": "`install.sh`", "Function Name": "<no specific function>", "Line Number": "8", "Fail": "The script is moving a file to a system directory without any form of verification or validation.", "Fix": "Implement a mechanism to verify the integrity of the file before moving it to a system directory." },
    { "Error Category": "🔒 Security Issues", "Priority": "🔴 High", "Filepath": "install.sh", "Function Name": "<no specific function>", "Line Number": "10", "Fail": "The script is asking for the OpenAI API key without any form of encryption or secure handling.", "Fix": "Implement a secure method for handling sensitive data like API keys." },
    { "Error Category": "⚠️ Error Handling Issues", "Priority": "🟠 Medium", "Filepath": "install.sh", "Function Name": "<no specific function>", "Line Number": "10", "Fail": "There is no error handling in case the user does not provide the OpenAI API key.", "Fix": "Add error handling to ensure that the user provides the OpenAI API key." },
    { "Error Category": "⚙️ Optimization Issues", "Priority": "🟠 Medium", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "run", "Line Number": "342", "Fail": "The run function is directly called in the main scope without any arguments.", "Fix": "Encapsulate the run function call within a main function and use argparse to handle command line arguments." },
    { "Error Category": "🚀 Performance Issues", "Priority": "🟠 Medium", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "get_files_changed", "Line Number": "159", "Fail": "The stderr redirection in the git command has been removed which can lead to performance issues if there are many error messages.", "Fix": "Add the stderr redirection back to the git command." },
    { "Error Category": "☑️ Consistency Issues", "Priority": "🟠 Medium", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "run", "Line Number": "201", "Fail": "The run function signature has been changed without any clear reason. The model parameter has been removed.", "Fix": "Revert the changes or provide a clear reason for the changes in the commit message." },
    { "Error Category": "🚀 Performance Issues", "Priority": "🟠 Medium", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "run", "Line Number": "340", "Fail": "The stderr redirection in the streamlit command has been removed which can lead to performance issues if there are many error messages.", "Fix": "Add the stderr redirection back to the streamlit command." },
    { "Error Category": "🌀 Complexity Issues", "Priority": "🟡 Low", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "get_file_diffs", "Line Number": "172", "Fail": "The print statement has been uncommented which can lead to unnecessary console logs.", "Fix": "Comment the print statement or use a logging library to control the log levels." },
    { "Error Category": "🌀 Complexity Issues", "Priority": "🟡 Low", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "run", "Line Number": "267", "Fail": "The message printed when no feedback is found has been changed without any clear reason.", "Fix": "Revert the changes or provide a clear reason for the changes in the commit message." },
    { "Error Category": "☑️ Consistency Issues", "Priority": "🟡 Low", "Filepath": "reviewme/ailinter/ailinter.py", "Function Name": "run", "Line Number": "324", "Fail": "The column names of the organized_feedback_df DataFrame have been changed without any clear reason.", "Fix": "Revert the changes or provide a clear reason for the changes in the commit message." }
];